# absolute path to dataset
path: "../yolo"

#train images
train: /home/ed/programming/python/opencv_bot/opencv_diepio_bot/yolo/images/train/ 

# path to validation images
val: /home/ed/programming/python/opencv_bot/opencv_diepio_bot/yolo/images/val/

# number of classes
nc: 4

# names of classes
name: ["y_cube", "r_tringle", "b_pentagon", "enemy_npc1" ]
