# absolute path to dataset
path: "../yolo"

#train images
train: /home/ed/programming/python/opencv_bot/opencv_diepio_bot/yolo/images/train/ 

# path to validation images
val: /home/ed/programming/python/opencv_bot/opencv_diepio_bot/yolo/images/val/

# number of classes
nc: 4

# names of classes
names:
    0: cube
    1: triangle
    2: pentagon
    3: enemy_npc1
